import { Iproducts } from './types/types';

const productsArr: Iproducts[] = [
  {
    id: '0',
    name: 'Lavazza',
    product: false,
    img: './assets/lavazza.png',
    quantity: '30',
    manufacturer: 'Италия',
    roasting: 'Средняя',
    grinding: 'Зерновой',
    price: '80',
    popular: 'Да',
  },
  {
    id: '1',
    name: 'Dallmayr',
    product: false,
    img: './assets/dalmaer.jpeg',
    quantity: '50',
    manufacturer: 'Германия',
    roasting: 'Средняя',
    grinding: 'Mолотый',
    price: '11',
    popular: 'Да',
  },
  {
    id: '2',
    name: 'Ipnosi',
    product: false,
    img: './assets/ipnosi.jpeg',
    quantity: '11',
    manufacturer: 'Армения',
    roasting: 'Средняя',
    grinding: 'Зерновой',
    price: '25',
    popular: 'Нет',
  },
  {
    id: '3',
    name: 'Jacobs',
    product: false,
    img: './assets/jacobs.jpeg',
    quantity: '95',
    manufacturer: 'США',
    roasting: 'Средняя',
    grinding: 'Молотый',
    price: '30',
    popular: 'Нет',
  },
  {
    id: '4',
    name: 'Grano',
    product: false,
    img: './assets/grano.jpeg',
    quantity: '80',
    manufacturer: 'Великобритания',
    roasting: 'Средняя',
    grinding: 'Зерновой',
    price: '35',
    popular: 'Да',
  },
  {
    id: '5',
    name: 'Carraro',
    product: false,
    img: '../assets/carraro.png',
    quantity: '30',
    manufacturer: 'Италия',
    roasting: 'Средняя',
    grinding: 'Зерновой',
    price: '50',
    popular: 'Да',
  },
  {
    id: '6',
    name: 'BUSHIDO',
    product: false,
    img: '../assets/bushido.jpeg',
    quantity: '60',
    manufacturer: 'Швейцария',
    roasting: 'Средняя',
    grinding: 'Зерновой',
    price: '75',
    popular: 'Да',
  },
  {
    id: '7',
    name: 'Kimbo',
    product: false,
    img: '../assets/kimbo.jpeg',
    quantity: '50',
    manufacturer: 'Италия',
    roasting: 'Tемная',
    grinding: 'Зерновой',
    price: '90',
    popular: 'Да',
  },
];

export default productsArr;
